---
version: "2.1"
services:
  nci:
    image: nci:local
    build:
      context: .
    container_name: nci-docker
    hostname: nci-tests
    environment:
      - PASSWORD_STORE_GPG_OPTS=--armor
    volumes:
      - ./ssh:/root/.ssh
      - ./gnupg:/root/.gnupg
      - ./secrets:/root/.password-store
      - ./data:/var/nci/data
      - /var/run/docker.sock:/var/run/docker.sock
    # command: tail -F anything
    ports:
      - "3007:3000"
    restart: always

